### PR TITLE
Changed filename id format

### PR DESCRIPTION
**Pull request by tikoflano**
I really like the idea behind this plugin and am interested in helping with it. This commit fixes the open issue #17 and it helps me check if the author is interested in continuing developing this.

### CODE REVIEW

**Comment by daita** [comment]
I like this. However I think it would be nice to let the admin configure the path using 

>      ./occ config:app:set --value 'Ymdhis' files_frommail folder_format

and using `$this->configService->getAppValue('date_format')` to retrieve the format:
https://github.com/nextcloud/files_frommail/blob/master/lib/Service/ConfigService.php#L82-L90
https://github.com/nextcloud/files_frommail/blob/master/lib/Service/ConfigService.php#L34-L38

**Comment by tikoflano** [comment]
I added the proposed changes.

**Comment by daita** [comment]
nice, can you set _'Y-m-d H:i:s'_ as default instead ?

**Comment by tikoflano** [comment]
Ok, now it is ready. I had a lot of troubles with the sign off requirement lol.

**Comment by daita** [comment]
Thanks for your work !

**Pull request merged**
